blank_issues_enabled: false

contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/imidll/selfshop.ms-catalog/discussions
    about: |
      Вопросы по использованию, архитектуре и идеи для обсуждения.
      Не используйте issues для общих вопросов.
